version: "3.3"
services:
  openvpn:
    image: stargazer/openvpn-docker
    ports:
      - "1194:1194"
    volumes:
      - ./config:/etc/openvpn
    cap_add:
      - NET_ADMIN
      - NET_RAW
  cloak:
    build: ./cloak-docker
    network_mode: "host"
    environment:
      - PORT=444
    volumes:
      - ./cloak:/config