version: "3.3"
services:
  openvpn:
    image: stargazer/openvpn-docker
    restart: unless-stopped
    ports:
      - "${OPENVPN_PORT}:1194"
    volumes:
      - ./configs/openvpn:/etc/openvpn
    cap_add:
      - NET_ADMIN
      - NET_RAW
  cloak:
    build: ./cloak
    network_mode: "host"
    restart: unless-stopped
    environment:
      - PORT=${CLOAK_PORT}
      - PROXY_BOOK=${PROXY_BOOK}
      - SPOOF_ADDRESS=${SPOOF_ADDRESS}
    volumes:
      - ./configs/cloak:/config

